source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'MilenaBooksApp' do
  use_frameworks!
    pod 'Alamofire', '~> 4.7'
    pod 'AlamofireObjectMapper', '~> 5.2'
    pod 'ObjectMapper', '~> 3.4'
    pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :branch => 'master'
    pod 'YNDropDownMenu'
end
